### ISSUE TITLE
Background image does not cover the top-right corner [BUG]

### ISSUE THREAD

**Issue by peterdev22** [Carbonateb/obsidian-encore-theme#31]
**Describe the Bug**
Background image/colour does not continue all the way into the top right corner of the window. This bug only happens on the main window.

Can be temporarily fixed by removing the right sidebar button using a snippet (I don't use right sidebar anyway):
```css
.sidebar-toggle-button.mod-right {
  display: none;
}

.workspace-tab-header-tab-list {
  transform: translate(2rem, 0);
}
```

**Relevant Screenshots**
<img width="192" alt="image" src="https://github.com/Carbonateb/obsidian-encore-theme/assets/95014170/fc4fd64e-294a-4bd9-9e6a-953f329eee06">

**To Reproduce**
Shows up when using any coloured theme within Encore.

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by noahtallen** [comment]
A fix which doesn't disable the button:

```css
.sidebar-toggle-button.mod-right {
    background-color: inherit !important;
}
```
